### ISSUE TITLE
error initiating pinfish with snakemake

### ISSUE THREAD

**Issue by AndrewWT** [nanoporetech/ont_tutorial_pinfish#1] opened 2019-04-05 16:52 UTC
Hello, I am getting the error below when I execute snakemake. I build the proper environment and get the tutorial to run but when I use my own data in the RawData and ReferenceData folders after updating the config.yaml file I am getting:

(Pinfish) -bash-4.2$ snakemake -j 1
Building DAG of jobs...
InputFunctionException in line 73 of /mnt/home/thom1524/Pinfish/Snakefile:
KeyError: 'AMC_annotation.gff.gz'
Wildcards:
unzipFile=AMC_annotation.gff.gz

It seems to me that the data I give it are not being opened or read. Any help would be much appreciated!

**Comment by sagrudd** [comment] 2019-04-08 10:56
Dear @AndrewWT - thanks for the message.
To help find the cause of the issue please could you kindly cut-and-paste the config.yaml (top bit, containing the pointer to your annotation file) and from the main working directory, please could you share the output of `find .` - I'll help you solve this!

**Comment by AndrewWT** [comment] 2019-04-08 13:48
> Dear @AndrewWT - thanks for the message.
> To help find the cause of the issue please could you kindly cut-and-paste the config.yaml (top bit, containing the pointer to your annotation file) and from the main working directory, please could you share the output of `find .` - I'll help you solve this!

Thanks for the help!  Here you go.


## Pipeline-specific parameters
threads: 16
pychopper: TRUE

# Input genome:
genome_fasta: "PESF00000000.fasta.gz"
genome_annot: "AMC_annotation.gff.gz"
# genome_fasta could either be (1) a URL to a genome assembly e.g. at enseml / ncbi
#                              (2) a filename corresponding to file that has been placed in the $ReferenceData folder

# CDNA or direct RNA reads in fastq format:
raw_fastq: "all_pass_Q.fastq.gz"





(base) -bash-4.2$ find .
.
./config.yaml
./RawData
./RawData/all_pass_Q.fastq.gz
./RawData/.gitignore
./ReferenceData
./ReferenceData/PESF00000000.fasta.gz
./ReferenceData/AMC_annotation.gff.gz
./.gitattributes
./src
./src/pychopper
./src/pychopper/data
./src/pychopper/data/cdna_barcodes.fas
./src/pychopper/.gitlab-ci.yml
./src/pychopper/ONT_logo.png
./src/pychopper/pytest.ini
./src/pychopper/MANIFEST.in
./src/pychopper/pychopper.egg-info
./src/pychopper/pychopper.egg-info/not-zip-safe
./src/pychopper/pychopper.egg-info/requires.txt
./src/pychopper/pychopper.egg-info/SOURCES.txt
./src/pychopper/pychopper.egg-info/dependency_links.txt
./src/pychopper/pychopper.egg-info/top_level.txt
./src/pychopper/pychopper.egg-info/PKG-INFO
./src/pychopper/scripts
./src/pychopper/scripts/cdna_classifier.py
./src/pychopper/scripts/__init__.py
./src/pychopper/setup.py
./src/pychopper/setup.cfg
./src/pychopper/docs
./src/pychopper/docs/index.rst
./src/pychopper/docs/conf.py
./src/pychopper/docs/Makefile
./src/pychopper/docs/cmd_tools.py
./src/pychopper/docs/make.bat
./src/pychopper/docs/.gitignore
./src/pychopper/docs/_static
./src/pychopper/docs/_static/.gitignore
./src/pychopper/COPYRIGHT
./src/pychopper/pychopper
./src/pychopper/pychopper/tests
./src/pychopper/pychopper/tests/__init__.py
./src/pychopper/pychopper/tests/test_integration.py
./src/pychopper/pychopper/tests/data
./src/pychopper/pychopper/tests/data/.gitignore
./src/pychopper/pychopper/tests/data/barcodes.fas
./src/pychopper/pychopper/tests/data/ref.fas
./src/pychopper/pychopper/tests/data/expected_output.fas
./src/pychopper/pychopper/tests/data/mismatch_scores.txt
./src/pychopper/pychopper/tests/test_detector.py
./src/pychopper/pychopper/__init__.py
./src/pychopper/pychopper/chopper.py
./src/pychopper/pychopper/utils.py
./src/pychopper/pychopper/report.py
./src/pychopper/pychopper/seq_detect.py
./src/pychopper/pychopper/seq_utils.py
./src/pychopper/LICENSE.md
./src/pychopper/README.md
./src/pychopper/Makefile
./src/pychopper/.git
./src/pychopper/.git/index
./src/pychopper/.git/logs
./src/pychopper/.git/logs/refs
./src/pychopper/.git/logs/refs/heads
./src/pychopper/.git/logs/refs/heads/master
./src/pychopper/.git/logs/refs/remotes
./src/pychopper/.git/logs/refs/remotes/origin
./src/pychopper/.git/logs/refs/remotes/origin/HEAD
./src/pychopper/.git/logs/HEAD
./src/pychopper/.git/HEAD
./src/pychopper/.git/packed-refs
./src/pychopper/.git/hooks
./src/pychopper/.git/hooks/prepare-commit-msg.sample
./src/pychopper/.git/hooks/commit-msg.sample
./src/pychopper/.git/hooks/pre-push.sample
./src/pychopper/.git/hooks/pre-rebase.sample
./src/pychopper/.git/hooks/pre-applypatch.sample
./src/pychopper/.git/hooks/applypatch-msg.sample
./src/pychopper/.git/hooks/pre-commit.sample
./src/pychopper/.git/hooks/update.sample
./src/pychopper/.git/hooks/post-update.sample
./src/pychopper/.git/hooks/fsmonitor-watchman.sample
./src/pychopper/.git/hooks/pre-receive.sample
./src/pychopper/.git/branches
./src/pychopper/.git/refs
./src/pychopper/.git/refs/heads
./src/pychopper/.git/refs/heads/master
./src/pychopper/.git/refs/remotes
./src/pychopper/.git/refs/remotes/origin
./src/pychopper/.git/refs/remotes/origin/HEAD
./src/pychopper/.git/refs/tags
./src/pychopper/.git/objects
./src/pychopper/.git/objects/info
./src/pychopper/.git/objects/pack
./src/pychopper/.git/objects/pack/pack-ce01e6341edc0e57e916d43fd2a18dc8157d8547.pack
./src/pychopper/.git/objects/pack/pack-ce01e6341edc0e57e916d43fd2a18dc8157d8547.idx
./src/pychopper/.git/description
./src/pychopper/.git/info
./src/pychopper/.git/info/exclude
./src/pychopper/.git/config
./src/pip-delete-this-directory.txt
./.git
./.git/config
./.git/index
./.git/logs
./.git/logs/refs
./.git/logs/refs/heads
./.git/logs/refs/heads/master
./.git/logs/refs/remotes
./.git/logs/refs/remotes/origin
./.git/logs/refs/remotes/origin/HEAD
./.git/logs/HEAD
./.git/branches
./.git/HEAD
./.git/description
./.git/refs
./.git/refs/remotes
./.git/refs/remotes/origin
./.git/refs/remotes/origin/HEAD
./.git/refs/heads
./.git/refs/heads/master
./.git/refs/tags
./.git/hooks
./.git/hooks/pre-push.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/post-merge
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/pre-commit.sample
./.git/hooks/post-commit
./.git/hooks/pre-receive.sample
./.git/hooks/update.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-push
./.git/hooks/commit-msg.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/post-checkout
./.git/hooks/pre-rebase.sample
./.git/packed-refs
./.git/objects
./.git/objects/d6
./.git/objects/d6/3c992cb07147b9bc00d1e097aa9ca8520ae0c5
./.git/objects/7e
./.git/objects/7e/1ef7361c0c425300666c33c07b395359100e58
./.git/objects/bb
./.git/objects/bb/16f70ae78fd3c78d142a73123c87f9d7061004
./.git/objects/bb/0b48ca27a76e80134d8565038f4f04aecc1709
./.git/objects/82
./.git/objects/82/aaf892221e8309be96933718cb14538c2ad289
./.git/objects/b8
./.git/objects/b8/7f397f0e2efbffcaad4c8d519c46132dc01ef2
./.git/objects/47
./.git/objects/47/062b5976147c57de2eb4c2977cfba9ae53cda5
./.git/objects/8b
./.git/objects/8b/921057b75e05ea45fdc64f0656f18ff3b41f46
./.git/objects/e5
./.git/objects/e5/49a50350bc2127c76e8e8da9135222176e6a3d
./.git/objects/5d
./.git/objects/5d/9154452f5f1f79f699d0d2c1d4e012e97a6b4b
./.git/objects/df
./.git/objects/df/115b2ac15d8145040f7ae47a4433b96167135a
./.git/objects/a0
./.git/objects/a0/490ed5a1ccb7c30e42a4c445a0dfc2a806941d
./.git/objects/2d
./.git/objects/2d/0f2cf155df442c66f0749bab019ace3a513d6d
./.git/objects/e8
./.git/objects/e8/f136f2edaaee20af06079e134157188a53b2b2
./.git/objects/6a
./.git/objects/6a/51270a7644a2a86bb1320d0d59abfd300655f1
./.git/objects/6a/2676c6cc5f2c7799bdbb893e0753bcf8256024
./.git/objects/37
./.git/objects/37/6fc0806506b87cbdd504e719bd121901aae418
./.git/objects/8e
./.git/objects/8e/b7f5bb8583b637e9f56e325698b5318d22a988
./.git/objects/8e/579541edb3817b488c8386f7aedb493d060627
./.git/objects/8e/764f900db5c2c6e9c31354434515258028d0db
./.git/objects/16
./.git/objects/16/f466072977652855511d350f174cf661c25d9e
./.git/objects/d1
./.git/objects/d1/077707c401a445b55c4c2958f62f2a021a5578
./.git/objects/53
./.git/objects/53/bfb065e316337d61e3fcb78afb96da7771f40e
./.git/objects/53/e02d2c11219aef138a92f828681fd24e3cb28d
./.git/objects/9f
./.git/objects/9f/836f9ee848e7826f45c336bdfc29e0d6843e8b
./.git/objects/fd
./.git/objects/fd/ff4a34f4671023cc40786e5eaa1badbbc2e160
./.git/objects/ac
./.git/objects/ac/46d1caf5060e0300063e1949d825614a90e2a0
./.git/objects/ac/0aeb8e677057250b3c943e050cafef7df5f619
./.git/objects/7f
./.git/objects/7f/d0a5104fa9ac2f91f3e42787035aa6f0ae57a4
./.git/objects/9b
./.git/objects/9b/b503de1c5410d1cd81477e871cf88869f47f12
./.git/objects/9b/367a7e58d49b83d49c629c40627912a8be3e1f
./.git/objects/57
./.git/objects/57/0e66294ef2be4a91b6c4e6b0645dcc84f64fe4
./.git/objects/d5
./.git/objects/d5/a9128be0af69289a26222328618aae00b160fe
./.git/objects/3c
./.git/objects/3c/195bf96902e3d44f0319761527fc162ad04d4f
./.git/objects/ba
./.git/objects/ba/038017a137517c101a0692eab3307d7173dbd8
./.git/objects/ef
./.git/objects/ef/f5ce09bd71b0a48e2cef5762ec830479760d79
./.git/objects/8a
./.git/objects/8a/441c3a5f6aa9b36d65446ffb76383b581c9e8b
./.git/objects/8a/b453263cd0b1411fd0400df237b02a20388319
./.git/objects/8a/93c77323e796d29479a84dfeccfc77aad161bf
./.git/objects/1b
./.git/objects/1b/75e4fb6a9e6b411d0bfff7926f9821fa31c1ed
./.git/objects/6e
./.git/objects/6e/b6cf81b8119e9d33cd662000ef180304beb54f
./.git/objects/39
./.git/objects/39/0666c56fab86fcee52be080fc97279e4dd680e
./.git/objects/76
./.git/objects/76/35a85f8d9f347f2ab2fd18aa2fbc65f689c691
./.git/objects/pack
./.git/objects/01
./.git/objects/01/fb51e19852046659c796b8ecca9f79ddddbb56
./.git/objects/a3
./.git/objects/a3/d4c578b3682fe920e1ec935e57ea247f41d91f
./.git/objects/a9
./.git/objects/a9/989efdaeb8d44e29981a162acc3b308b880de1
./.git/objects/cb
./.git/objects/cb/14d9fd3cdf35ddaf7ce542c3bf0082c982bfdb
./.git/objects/06
./.git/objects/06/6b249ca2d2728bffa9ca2025bf12f1a2c84094
./.git/objects/a4
./.git/objects/a4/cdbcde7338bd1fc5548bb794b57cef0a2573e9
./.git/objects/db
./.git/objects/db/06f0ada351e0379a030c5c6ef459dcc5cf0bd6
./.git/objects/b6
./.git/objects/b6/79930a57595f34fb8aa881bb2ab0335731f09f
./.git/objects/b6/246d78dfa1c330b1cf3d541d69b04d0dc8f9aa
./.git/objects/34
./.git/objects/34/9ecad4d502b864738a1fa28b67593becdba1ff
./.git/objects/34/30ed494c00272675d7447398cf7fa9f5684bee
./.git/objects/6b
./.git/objects/6b/58d51fd80926a8d4312cdbd731de582c5bde0a
./.git/objects/3d
./.git/objects/3d/0b3bcc87d02278615ef7cac253a780d7a615a0
./.git/objects/15
./.git/objects/15/b69e1e63d1155a88ee8e34fcbe8065def84782
./.git/objects/15/29a25d7ce7b315c65ac9f4e7de33aa2a0a95f7
./.git/objects/d8
./.git/objects/d8/9cfc4eea2b3c211fe6ef21cf7a6493864f9de8
./.git/objects/7a
./.git/objects/7a/581224954066af7ed295b438fffd322538ddc7
./.git/objects/d2
./.git/objects/d2/4e8308c13bcac74bd5a6c242d0ebb9c21dc6e6
./.git/objects/4a
./.git/objects/4a/3aa981e03381075b21786226a2dcc036e8caa0
./.git/objects/ec
./.git/objects/ec/f4424b747e92d677c095433985b99d3db4d76c
./.git/objects/c7
./.git/objects/c7/4fb1f8f22f1f89bbb822454a4b0e3bb09900c8
./.git/objects/f1
./.git/objects/f1/ce77a18541379770df6e143b3c1303e0b4d7c8
./.git/objects/a6
./.git/objects/a6/12ad9813b006ce81d1ee438dd784da99a54007
./.git/objects/a6/793c6b08e77e83d61d9d4f67ada72a39a895f9
./.git/objects/e3
./.git/objects/e3/104a0cd7d87ead4c701dcf7b7bf85f988bd63c
./.git/objects/e4
./.git/objects/e4/b0c3399beea1f506dd186c8a1681be9c81601d
./.git/objects/74
./.git/objects/74/e69cff43a38513c864afba2b744262f9f0a7e1
./.git/objects/03
./.git/objects/03/3e42af5df861e5a8bc547768fd01cdf90f6c9c
./.git/objects/a1
./.git/objects/a1/cb537d7fab230e3a8ef78b32e59b3ff1935ff7
./.git/objects/f6
./.git/objects/f6/48df8e09515c8ace5d24b0e440b0730c363789
./.git/objects/28
./.git/objects/28/5a8345f2c25daaf7524a260486337901c53fcf
./.git/objects/4f
./.git/objects/4f/7e6b7d36e758c7fa204b8894e9242a2d75c885
./.git/objects/3a
./.git/objects/3a/694368b7480e9c6421a0c20114a8e99a7fdf48
./.git/objects/bc
./.git/objects/bc/a3c34807ac1cf4556eb8b3cb64bce2641d849e
./.git/objects/bc/1dccc226b1b3280daecf3fc47ca61870b0d3d1
./.git/objects/14
./.git/objects/14/6c0370f85edfea6578c2f56e1e02f060074073
./.git/objects/87
./.git/objects/87/36c21ee8c7dc41ff69feac19c3e2780c961734
./.git/objects/3e
./.git/objects/3e/d981e1b17f4df385adf3cad7ddb78ddd431971
./.git/objects/d3
./.git/objects/d3/23a736a85b6c8231ffab88b09bf23ebca53bae
./.git/objects/9d
./.git/objects/9d/b0c589c6b3f715b1730054ca41e7f3e748a98d
./.git/objects/26
./.git/objects/26/03e41ffe59f728b8e5f7c658643963fa5d2289
./.git/objects/fb
./.git/objects/fb/7467cdaf91f717932d1b71a9ce0a8ee4ba8b4b
./.git/objects/cd
./.git/objects/cd/8003f435af91fcfe950f92d122bc54e2177e11
./.git/objects/07
./.git/objects/07/2512bffe58faed9a8a353336062ebdf355d533
./.git/objects/48
./.git/objects/48/cfe507a4d0df512a2a79fc37a9c83cb1e6ca53
./.git/objects/48/c9c86cece2a7cc2fc616de5163602f628b49ff
./.git/objects/info
./.git/objects/1c
./.git/objects/1c/fe1821b28f2e6d9fe44b1f3142d26c0a509c99
./.git/objects/1c/db035499591315ba297cc0ad0e312d244e7523
./.git/objects/93
./.git/objects/93/3a72ab66560962795d14d88a73b0e03fe894c0
./.git/objects/5f
./.git/objects/5f/9d9bf939c2c8bd32f3c89c38eabda768d1458d
./.git/objects/a8
./.git/objects/a8/37131805d18534cdb647a51e8a44bdf1b88e83
./.git/objects/99
./.git/objects/99/99c7ad86a1f1acb007e465b3baee80282d607d
./.git/objects/9c
./.git/objects/9c/c8c4664cee60433d853edb4fa1e53b5d77d9d2
./.git/objects/fe
./.git/objects/fe/1551b160e5a3a07c8784531ef8933324c47b72
./.git/objects/13
./.git/objects/13/4601942d3cd0e7f26881160af711f358218296
./.git/objects/19
./.git/objects/19/f28e8dd65e32df4833a914ab72c8486f4dc895
./.git/info
./.git/info/exclude
./.git/lfs
./.git/lfs/incomplete
./.git/lfs/tmp
./.git/lfs/objects
./.git/lfs/objects/47
./.git/lfs/objects/47/14
./.git/lfs/objects/47/14/47143c679f4a0e6fd14d878f78315e0477f8ee26c6db910f7825b1deea9eb5e1
./Static
./Static/TutorialPostamble.md
./Static/Images
./Static/Images/FolderLayout.png
./Static/Images/KnitIt.png
./Static/Images/igv.png
./Static/Images/ConfigYamlParameters.png
./Static/Images/dag.png
./Static/Images/ONT_logo.png
./Static/Images/sashimi.png
./Static/ont_tutorial.css
./Static/Bibliography.bib
./Static/TutorialPreamble.md
./Snakefile
./.gitignore
./Nanopore_Pinfish_Tutorial.Rmd
./environment.yaml
./LICENSE
./README.md
./.snakemake
./.snakemake/singularity
./.snakemake/shadow
./.snakemake/log
./.snakemake/log/2019-04-04T153222.340111.snakemake.log
./.snakemake/log/2019-04-04T153440.230141.snakemake.log
./.snakemake/metadata
./.snakemake/conda-archive
./.snakemake/conda
./.snakemake/locks

**Comment by sagrudd** [comment] 2019-04-08 16:01
Dear @AndrewWT - awesome, thanks!  I have been able to reproduce your error message

You have identified a bug in the snakemake file - congratulations! I'll get this sorted tomorrow and will update you when the fix is in place. Thanks for your patience here!

**Comment by AndrewWT** [comment] 2019-04-08 16:02
Glad I can help!  And thanks so much.

Drew

--
Andrew W. Thompson, Ph.D.
Postdoctoral Researcher
Braasch Lab, Michigan State University
Website<http://drewt1023.wixsite.com/andrewwthompson>

**Comment by AndrewWT** [comment] 2019-04-09 18:19
Thanks, that helped and it proceeded until I get this error below.  Is it trying to download a remote file?  My files are local in the Pinfish Reference Data.

[Tue Apr  9 14:16:22 2019]
rule DownloadRemoteFile:
    input: nanoporetech.com
    output: ReferenceData/AMC_annotation.gff.gz
    jobid: 9
    wildcards: downloadFile=AMC_annotation.gff.gz

Downloading from remote: nanoporetech.com
Traceback (most recent call last):
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/__init__.py", line 541, in snakemake
    report=report)
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/workflow.py", line 656, in execute
    success = scheduler.schedule()
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/scheduler.py", line 286, in schedule
    self.run(job)
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/scheduler.py", line 302, in run
    error_callback=self._error)
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/executors.py", line 271, in run
    future = self.run_single_job(job)
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/executors.py", line 297, in run_single_job
    run_wrapper, *self.job_args_and_prepare(job))
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/executors.py", line 277, in job_args_and_prepare
    job.prepare()
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/jobs.py", line 596, in prepare
    self.download_remote_input()
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/jobs.py", line 571, in download_remote_input
    f.download_from_remote()
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/io.py", line 324, in download_from_remote
    self.remote_object.download()
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/site-packages/snakemake/remote/HTTP.py", line 175, in download
    os.makedirs(os.path.dirname(self.local_path), exist_ok=True)
  File "/mnt/home/thom1524/miniconda3/envs/Pinfish/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by sagrudd** [comment] 2019-04-10 05:37
Hei Drew, we're getting closer - this message shows that the file `./ReferenceData/AMC_annotation.gff.gz` cannot be found by the `snakemake` process - so it tries to download the file. Since a URL has not been provided in the `config.yaml` it chokes. Please can you check the content of your ReferenceData directory?

**Comment by AndrewWT** [comment] 2019-04-10 20:55
Thanks!  It looks like something weird happened with that file.  Once I replaced it, it is working good now.

 

Drew

**Comment by sagrudd** [comment] 2019-04-11 05:37
Great - thanks for the update!

**Closed by sagrudd** 2019-04-11 05:37 UTC

**Comment by sagrudd** [comment] 2019-05-17 09:27
Dear Andrew, I haven't heard anything back since the last suggestion. Have you been able to solve the analysis problem? Can I close this issue? Thanks - Stephen

**Comment by AndrewWT** [comment] 2019-05-17 13:36
Hi Stephen, it seems to be working! Thank you.

 

Drew

 

-- 

Andrew W. Thompson, Ph.D.

Postdoctoral Researcher

Braasch Lab, Michigan State University

Website
